### ISSUE TITLE
Failed to Mount on High Sierra 10.13.6 (17G9016)

### ISSUE THREAD

**Issue by nyhtml** [chris1111/Command-Line-EFI-Mounter#1]
I could not get the program to work on macOS High Sierra 0.13.6 (17G9016) so I figured it had to do with "sudo" this was done to fix it.

1. Show Package Contents
2. Open CommandLineEFIMounter.sh
3. Locate "`diskutil list`" on 19
4. Amend to "`sudo diskutil list`" on line 19
5. Locate "`diskutil mount ${target}`" on line 30
6. Amend to "`sudo diskutil mount ${target}`" on line 30
7. Save.

When runs now, it will prompt for a password (only once) before listing the partitions.
**Demo**: [Command Line EFI Mounter | GixxerPC](https://youtu.be/S3JAs3JoZmQ)

**Comment by chris1111** [comment]
Thanks Commit change on release V3 
https://github.com/chris1111/Command-Line-EFI-Mounter/releases/tag/V3

**Comment by nyhtml** [comment]
Great. I could not figure out where you had the two instances of "Good By" in the app.
I kept looking and saw one in Main.sh which fixed but the other is well hidden. I have Catalina 10.15.3 at school so I will check it January to see if launches.

![Screen Shot 2019-12-20 at 10 34 37 PM](https://user-images.githubusercontent.com/2177262/71302466-2828d100-2379-11ea-935b-712f8fd0183d.png)
![Screen Shot 2019-12-20 at 10 34 51 PM](https://user-images.githubusercontent.com/2177262/71302461-19dab500-2379-11ea-85a0-aacad91d7c1f.png)

**Comment by chris1111** [comment]
is in the Main.sh script
![Capture d’écran, le 2019-12-21 à 06 49 05](https://user-images.githubusercontent.com/6248794/71307543-0998f900-23be-11ea-9ecc-2b0d978830ae.png)

Only thing is the Progress bar not working in macOS Catalina 🤨

**Comment by chris1111** [comment]
Ok got it see release V4 😀
Added progress bar in AppleScript
https://github.com/chris1111/Command-Line-EFI-Mounter/releases/tag/V4
