### ISSUE TITLE
strange characters

### ISSUE THREAD

**Issue by luigisvideos** [chris1111/Command-Line-EFI-Mounter#2]
As visible in the attached screen, strange characters are printed in the terminal.

![Schermata 2022-05-21 alle 00 42 54](https://user-images.githubusercontent.com/11027614/169621422-e9398442-d72c-46ac-9f96-9fb2395123f8.png)

**Comment by chris1111** [comment]
it's not so strange, it's the command  to display the colors on the text
what version of macOS are you using? Are you on a VM
NO issue here on macOS Monterey 12.4
![Screen Shot 2022-05-20 at 7 15 56 PM](https://user-images.githubusercontent.com/6248794/169623652-c8b9e2ea-0005-4cc7-9353-90f0d7cd8d35.png)

**Comment by luigisvideos** [comment]
I am on Monterey 12.4, no virtualization

**Comment by nyhtml** [comment]
It seems that @luigisvideos has the OS language set for Italian.

Do you have your OS set for English or French, @chris1111 and is zsh set for your Terminal?

**Comment by chris1111** [comment]
And no issue on latest Ventura

![Screenshot 2023-05-06 at 00 09 23](https://user-images.githubusercontent.com/6248794/236599011-e70885b5-7f38-4f05-8494-0624de5c883c.png)
